Repository aces/DICAT, pull requests merged in 2018-08, with the labels that each got.

#96 Modifying the README for the executables location
  README.md
Labels: type:documentation

#95 Adding possibility to run DICAT on a several studies from the command line
  README.md
  dicat/dicom_anonymizer_frame.py
  dicat/lib/dicom_anonymizer_methods.py
  dicat/mass_deidentify.py
  docs/images/mass_deidentify_help.png
Labels: prio:high, type:add_to_release_notes, type:new_feature

#103 [DICOM deidentifier] Removing deprecated dcmtk methods
  dicat/dicom_anonymizer_frame.py
  dicat/lib/dicom_anonymizer_methods.py
Labels: prio:normal, type:bugfix, type:cleanup

#100 [Documentation] Update README
  README.md
Labels: prio:normal, type:cleanup, type:documentation

#101 [DICOM deidentifier] Removing leading and trailing spaces from PatientName and other DICOM fields
  dicat/lib/dicom_anonymizer_methods.py
Labels: prio:normal, type:bugfix

#105 Create LICENSE
  LICENSE
Labels: prio:low, type:documentation, type:new_feature
